trigger:
  branches:
    include:
    - master
  paths:
    include:
    - images/*

stages:
- stage: Build
  jobs:
  - job: A
    steps:


- stage: Deploy
  dependsOn: Build    # this stage runs after Test
