trigger:
  branches:
    include:
    - master
  paths:
    include:
    - images/*
  
variables:
- group: AWS

stages:
- stage: Build
  jobs:
  - job: 
    steps:
      - task: PackerTool@0
        inputs:
          version:
      
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'ls $(Build.SourcesDirectory)'

      - task: Packer@1
        inputs:
          connectedServiceType: 'aws'
          connectedServiceAWS: 'aws'
          templatePath: '$(Build.SourcesDirectory)/images/image.json'
          command: 'build'
          force: true
      
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)/images'
          ArtifactName: 'manifest'
          publishLocation: 'Container'

- stage: Build
  jobs:
  - job: 
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          downloadPath: '$(System.ArtifactsDirectory)'
          artifactName: 'manifest'
      
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            AMI_ID=$(jq -r '.builds[-1].artifact_id' $(System.ArtifactsDirectory)/manifest/manifest.json | cut -d ":" -f2)
            echo $AMI_ID